config/urls.py
from unittest.mock import patch
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # rutas relacionadas a la página principal tales como dashboard
    path('', include('core.homepage.urls')),
    # rutas relacionadas a los accesos del sistema, tales como ingresar, registrar
    path('access/', include('core.access_system.urls')),
    # rutas relacionadas a los proveedores tales como registrarlos, eliminarlos
    path('supplier/', include('core.supplier.urls')),
    # rutas relacionadas a los productos tales como registrar, eliminar, actualizar
    path('product/', include('core.product.urls')),
    # rutas relacionadas a la tienda tales como visualizar producto, comprar producto
    path('shop/', include('core.store.urls')),
    # rutas relacionadas a el estado actual de envio de los productos
    path('send/', include('core.status_send.urls')),
    # rutas relacionadas a las garantías de los productos e incidentes
    path('warranty/', include('core.warranty.urls')),
    # rutas relacionadas a la cantidad de productos disponibles en el sistema
    path('stock/', include('core.stock.urls')),
    # rutas relacionadas con el usuario
    path('user/', include('core.user.urls')),
    # rutas relacionadas al color de la página
    path('color-page/', include('core.colorpage.urls')),
    # rutas relacionadas con la facturación del usuario
    path('sale/', include('core.sale.urls')),
    # rutas relacionadas con la subida de facturas al sistema
    path('purchase/', include('core.purchase.urls')),
    # rutas relacionadas con la replicación automática de los datos
    path('data-application/', include('core.data.urls')),
    # rutas relacionadas a la administración de los usuarios
    path('user-admin/', include('core.user_admin.urls')),
    # rutas relacionadas con la administración de la aplicacion
    path('admin_site/', include('core.admin_site.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/access_system/urls.py
from django.urls import path
from core.access_system.views.change_password.views import ChangePasswordUseriew
from core.access_system.views.login.views import LoginView
from core.access_system.views.logout.views import *
from core.access_system.views.reset_password.views import ResetPasswordEmailiew
from core.access_system.views.signin.views import SignInView

app_name = 'access'
urlpatterns = [
    # paths for the loginform
    path('login/', LoginView.as_view(), name='Login'),
    # paths for the signinform
    path('signin/', SignInView.as_view(), name='signin'),
    # rutas para cerrar sesión
    path('logout/', LogoutUserView.as_view(), name='logout'),
    # ruta que nos permite enviar un correo al usuario para reestablecer su contraseña
    path('reset-pwd/', ResetPasswordEmailiew.as_view(), name='reset_pwd'),
    # ruta para cambiar la contraseña con el token recibido por correo
    path('change-password/<str:token>/', ChangePasswordUseriew.as_view(), name='change_pwd'),
    # ruta para eliminar todas las sesiones del usuario
    path('logout/all', LogoutAllSessionUserView.as_view(), name='logout_all')
]

core/access_system/models.py
from django.db import models

# Create your models here.

core/access_system/forms/form.py
from django import forms
from core.app_functions.data_replication import is_actual_state_autoreplication
from core.user.models import User
from django.contrib.auth.models import Group


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 
            'password', 'image', 'date_birthday', 'gender']
        
        widgets = {
            'password' : forms.PasswordInput(),
            'date_birthday' : forms.DateInput(attrs={
                'type' : 'date'
            })
        }
    
    #sobreescritura del método save para mandar al front-end los datos de estado del registro
    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                # obtenemos la contraseña del usuario
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                # guardamos el usuario y verificamos que exista
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = User.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password(pwd)
                # obtenemos la contraseña, la encriptamos y la guardamos
                u.save()
                client_group = Group.objects.get(name = 'Client')
                u.groups.add(client_group)
                if is_actual_state_autoreplication():
                    u.save(using = 'mirror_database')
                # asignamos un grupo por defecto en los usuarios
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

core/access_system/forms/form_change_pwd.py
from django import forms


class ChangePasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Ingrese la nueva contraseña',
        'class': 'form-control',
        'autocomplete': 'off'
    }))

    confirmPassword = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirma la nueva contraseña',
        'class': 'form-control',
        'autocomplete': 'off'
    }))

core/access_system/forms/form_reset_pwd.py
from django import forms
from core.user.models import User


# formulario del reseteo de la contraseña ingresando el username
class UserResetPwdForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']
        
        widgets = {
            'username' : forms.TextInput(attrs={
                'class' : 'form-control',
                'placeholder' : 'Ingresa el username'
                })
        }
    
    

core/access_system/views/change_password/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import FormView
from django.urls import reverse_lazy
from core.access_system.forms.form_change_pwd import ChangePasswordForm
from core.app_functions.data_replication import is_actual_state_autoreplication
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.user.models import User
from django.db import transaction
import uuid


# vista que cambia la contraseña y el token del usuario
class ChangePasswordUseriew(EmergencyModeMixin, FormView, ObtainColorMixin):
    template_name = 'change_password.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('app_views:homepage')


    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # sobreecsritura del método get para en caso de un link
    # inválido los mande a una página de 404
    def get(self, request, *args, **kwargs):
        user_token = self.kwargs['token']
        if User.objects.filter(token = user_token).exists():
            return super().get(request, *args, **kwargs)
        return HttpResponseRedirect(reverse_lazy('app_views:404_page'))
    

    # método que actualiza la contraseña y el token del usuario
    def update_password_token_user(self, new_password):
        data = {}
        try:
            with transaction.atomic():
                user = User.objects.get(token = self.kwargs['token'])
                user.set_password(new_password)
                user.token = uuid.uuid4()
                user.save()
                if is_actual_state_autoreplication():
                    user.save(using = 'mirror_database')
                data['success'] = reverse_lazy('access:Login')
        except Exception as e:
            data['error'] = str(e)
        return data
    
    # sobreecsritura del método post para 
    def post(self, request, *args, **kwargs):
        data = {}
        new_password = request.POST['id_password']
        confirm_password = request.POST['id_confirmPassword']
        if new_password == confirm_password:
            data = self.update_password_token_user(new_password)
        else:
            data['error'] = 'Las contraseñas no coinciden'
        print(data)
        return JsonResponse(data, safe=True)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Formulario de cambio de contraseña"
        context['color'] = self.get_number_color()
        return context
    

core/access_system/views/login/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin



class LoginView(EmergencyModeMixin, FormView, ObtainColorMixin):
    template_name = 'login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('app_views:dashboard_user')


    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.success_url)
    
    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        data = {}
        user = authenticate(request, username=username, password=password)
        if user is None:
            data['error'] = 'Usuario o contraseña no válidos'
        else:
            login(request, user)
            data['success'] = self.success_url
        return JsonResponse(data, safe=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Login"
        context['color'] = self.get_number_color()
        return context
    

core/access_system/views/logout/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.sessions.models import Session
from core.mixins.emergency_mixin import EmergencyModeMixin
from django.views.generic.base import View


class LogoutUserView(EmergencyModeMixin, LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy('app_views:homepage')
    template_name = 'index.html'

class LogoutAllSessionUserView(EmergencyModeMixin, LoginRequiredMixin, View):
    next_page = reverse_lazy('app_views:homepage')

    def dispatch(self, request, *args, **kwargs):
        session_query = Session.objects.all()
        for session in session_query:
            user_key = session.get_decoded().get('_auth_user_id')
            if self.request.user.pk == int(user_key):
                session.get_decoded()
                session.delete()
        return HttpResponseRedirect(self.next_page)

core/access_system/views/reset_password/views.py
from email.mime.multipart import MIMEMultipart
from http import server
import smtplib
import uuid
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import FormView
from django.urls import reverse_lazy
from core.access_system.forms.form_reset_pwd import UserResetPwdForm
from core.app_functions.data_replication import is_actual_state_autoreplication
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.user.models import User
from django.template.loader import render_to_string
from email.mime.text import MIMEText
import threading


class ResetPasswordEmailiew(EmergencyModeMixin, FormView, ObtainColorMixin):
    template_name = 'reset_password_email.html'
    form_class = UserResetPwdForm
    success_url = reverse_lazy('app_views:homepage')


    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    
    # método secundario que envia el correo con hilos
    def send_email_thread(self, user : User):
        try: 
            URL = settings.DOMAIN if not settings.DEBUG else self.request.META['HTTP_HOST']
            mailServer = smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT)
            mailServer.ehlo()
            mailServer.starttls()
            mailServer.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)
            email_to = user.email
            mensaje = MIMEMultipart()
            mensaje['From'] = settings.EMAIL_HOST_USER
            mensaje['To'] = email_to
            mensaje['Subject'] = 'Reseteo de contraseña'
            content = render_to_string('template_email_pass.html', {
                'user': user,
                'link_resetpwd': 'http://{}/access/change-password/{}/'.format(URL, str(user.token)),
                'link_home': 'http://{}'.format(URL)
            })
            mensaje.attach(MIMEText(content, 'html'))
            mailServer.sendmail(settings.EMAIL_HOST_USER, email_to, mensaje.as_string())
            mailServer.quit()
        except Exception as e:
            print(str(e))

    
    
    # método principal que envia un correo electrónico a la persona para reestablecer la contraseña
    def send_email(self, user:User):
        user = user[0]
        user.token = uuid.uuid4()
        user.save()
        if is_actual_state_autoreplication():
            user.save(using='mirror_database')
        thread = threading.Thread(target=self.send_email_thread, args=(user,))
        thread.start()


    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        data = {}
        user = User.objects.filter(username = username)
        if user.exists():
            try:
                self.send_email(user)
                data['success'] = self.success_url
            except Exception as e:
                data['error'] = str(e)
        else:
            data['error'] = 'Usuario no válido'
        return JsonResponse(data, safe=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "¿Olvidaste tu contraseña?"
        context['color'] = self.get_number_color()
        return context
    

core/access_system/views/signin/views.py
from django.http import JsonResponse
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from core.access_system.forms.form import UserForm
from core.user.models import User
from core.classes.obtain_color import ObtainColorMixin
from django.db import transaction



class SignInView(CreateView, ObtainColorMixin):
    model = User
    success_url = reverse_lazy('app_views:homepage')
    template_name = 'signin.html'

    def get_form(self):
        return super().get_form(UserForm)
    
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            # obtención de los datos
            with transaction.atomic():
                form = self.get_form()
                # guardado de los datos
                data = form.save()
                if 'error' in data:
                    transaction.set_rollback(True)
                    transaction.set_rollback(True, using = 'mirror_database')
        except Exception as e:
            data['error'] = str(e)
        # regreso de la respuesta del servidor
        return JsonResponse(data, safe=False)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Sign In"
        context['cancel'] = reverse_lazy('app_views:homepage')
        context['success'] = self.success_url
        context['action'] = 'register' 
        context['color'] = self.get_number_color()
        context['btn'] = 'Crear'
        return context

core/access_system/templates/change_password.html
{% extends 'baseView.html' %}
{% load static %}
{% load widget_tweaks %}
<!--Bloques para inclusiones de librerias-->

{% block head %}
<link rel="stylesheet" href="{% static 'css/stylesLogin.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout main-card">
    <div class="form-group card card-body" style="margin-top: 25%;">
        <h1>{{title}}</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label>{{ field.label }}:</label>
                {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-danger" id="submit">Cambiar contraseña</button>
            <a class="btn btn-secondary" href="/" role="button">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/validate_change_pwd.js' %}"></script>
{% endblock %}

core/access_system/templates/login.html
{% extends 'baseView.html' %}
{% load static %}
{% load widget_tweaks %}
<!--Bloques para inclusiones de librerias-->

{% block head %}
<link rel="stylesheet" href="{% static 'css/stylesLogin.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout main-card">
    <div class="form-group card card-body" style="margin-top: 25%;">
        <h1>{{title}}</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label>{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off'}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-danger" id="submit">Login</button>
            <a class="btn btn-secondary" href="{% url 'access:reset_pwd' %}" role="button">¿Olvidaste tu contraseña?</a>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/validate_session.js' %}"></script>
{% endblock %}

core/access_system/templates/reset_password_email.html
{% extends 'baseView.html' %}
{% load static %}
{% load widget_tweaks %}
<!--Bloques para inclusiones de librerias-->

{% block head %}
<link rel="stylesheet" href="{% static 'css/stylesLogin.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout main-card">
    <div class="form-group card card-body" style="margin-top: 25%;">
        <h1>{{title}}</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Username</label>
                {{form.username}}
            </div>
            <button type="submit" class="btn btn-primary" id="submit">Enviar correo</button>
            <a class="btn btn-danger" href="{% url 'access:Login' %}" role="button">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/validate_send_email.js' %}"></script>
{% endblock %}

core/access_system/templates/signin.html
{% extends 'baseView.html'%}
{% load static %}
{% load widget_tweaks %}

<!-- bloque de archivos estaticos a cargar -->
{% block head %}
<link rel="stylesheet" href="{% static 'css/signin/styles.css' %}">
<script src="{% static 'js/functions.js' %}"></script>
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <div class="image">
            <img src="{% static 'img/user.png' %}" id="user-image">
        </div>
        <input type="hidden" id="value" value="{{success}}">
        <input type="hidden" id="action" value="{{action}}">
        <form method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label>{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off'}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">{{btn}}</button>
            <a href="{{cancel}}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/validate_action.js' %}"></script>
<script src="{% static 'js/limit_img_size.js' %}"></script>
{% endblock %}