config/urls.py
from unittest.mock import patch
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # rutas relacionadas a la página principal tales como dashboard
    path('', include('core.homepage.urls')),
    # rutas relacionadas a los accesos del sistema, tales como ingresar, registrar
    path('access/', include('core.access_system.urls')),
    # rutas relacionadas a los proveedores tales como registrarlos, eliminarlos
    path('supplier/', include('core.supplier.urls')),
    # rutas relacionadas a los productos tales como registrar, eliminar, actualizar
    path('product/', include('core.product.urls')),
    # rutas relacionadas a la tienda tales como visualizar producto, comprar producto
    path('shop/', include('core.store.urls')),
    # rutas relacionadas a el estado actual de envio de los productos
    path('send/', include('core.status_send.urls')),
    # rutas relacionadas a las garantías de los productos e incidentes
    path('warranty/', include('core.warranty.urls')),
    # rutas relacionadas a la cantidad de productos disponibles en el sistema
    path('stock/', include('core.stock.urls')),
    # rutas relacionadas con el usuario
    path('user/', include('core.user.urls')),
    # rutas relacionadas al color de la página
    path('color-page/', include('core.colorpage.urls')),
    # rutas relacionadas con la facturación del usuario
    path('sale/', include('core.sale.urls')),
    # rutas relacionadas con la subida de facturas al sistema
    path('purchase/', include('core.purchase.urls')),
    # rutas relacionadas con la replicación automática de los datos
    path('data-application/', include('core.data.urls')),
    # rutas relacionadas a la administración de los usuarios
    path('user-admin/', include('core.user_admin.urls')),
    # rutas relacionadas con la administración de la aplicacion
    path('admin_site/', include('core.admin_site.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/purchase/urls.py
from django.urls import path
from core.purchase.views.compare_sales_purchases.views import CompareSalesPurchasesView
from core.purchase.views.list_invoices_system.views import ListInvoiceSystemView

from core.purchase.views.options_purchase.views import OptionsPurchaseView
from core.purchase.views.upload_invoice.views import UpdloadPurchaseView


app_name = "purchase"
urlpatterns = [
    # ruta general para mostrar la pantalla de subida de las compras
    path("options/", OptionsPurchaseView.as_view(), name="options"),
    #ruta para subir las facturas
    path("upload-invoice/", UpdloadPurchaseView.as_view(), name="upload"),
    # ruta para listar todas las facturas del sistema
    path("list-invoices/", ListInvoiceSystemView.as_view(), name="list_invoices"),
    # ruta para comparar los gastos e ingresos del mes actual
    path("comparation/", CompareSalesPurchasesView.as_view(), name="comparation")
]

core/purchase/models.py
from datetime import datetime
from django.db import models
from core.product.models import Product, Size


# table for the purchase
class Purchase(models.Model):
    id = models.BigAutoField(primary_key=True)
    date_purchase = models.DateField(default=datetime.now, verbose_name='Fecha factura')
    subtotal = models.DecimalField(max_digits=18, decimal_places=2, verbose_name='Subtotal')
    iva = models.DecimalField(max_digits=3, decimal_places=2, verbose_name='Iva', default=0.16)
    total = models.DecimalField(max_digits=18, decimal_places=2, verbose_name='Total')

    class Meta:
        verbose_name = "Purchase"
        verbose_name_plural = 'Purchases'
        ordering = ['id']
        db_table = 'purchase'

# table for the detail of the sale
class DetailPurchase(models.Model):
    id = models.BigAutoField(primary_key=True)
    purchase = models.ForeignKey(Purchase, verbose_name='Número factura', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, verbose_name='Producto', on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Precio')
    ammount = models.IntegerField(default=0, verbose_name='Cantidad')
    subtotal = models.DecimalField(max_digits=18, decimal_places=2, verbose_name='Subtotal')
    size = models.ForeignKey(Size, verbose_name='Talla', on_delete=models.PROTECT, null=True)
    color = models.CharField(max_length=8, default='')

    class Meta:
        verbose_name = "DetailPurchase"
        verbose_name_plural = 'DetailPurchase'
        ordering = ['id']
        db_table = 'detail_purchase'

core/purchase/views/compare_sales_purchases/views.py
from datetime import datetime
from django.urls import reverse_lazy
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.purchase.models import Purchase
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from core.sale.models import Sale
from django.db.models import Sum

# vista que nos permitirá comparar nuestros gastos y nuestras ventas
class CompareSalesPurchasesView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, TemplateView):
    template_name = "compare_sales_purchases.html"
    login_url: reverse_lazy("access:Login")
    group_permisson = 'Administrator'

    # método que nos regresa el nombre del mes actual
    def get_name_month(self):
        date_month = datetime.now()
        date_month = date_month.month
        match date_month:
            case 1:
                return "Enero"
            case 2:
                return "Febrero"
            case 3:
                return "Marzo"
            case 4:
                return "Abril"
            case 5:
                return "Mayo"
            case 6:
                return "Junio"
            case 7:
                return "Julio"
            case 8:
                return "Agosto"
            case 9:
                return "Septiembre"
            case 10:
                return "Octubre"
            case 11:
                return "Noviembre"
            case 12:
                return "Diciembre"
    
    # método que nos devuelve la cantidad (total vendido) del mes  y el año actual
    def get_money_related_sales(self):
        date_month = datetime.now().month
        date_year = datetime.now().year
        sales_month = Sale.objects.filter(
            date_sale__year = date_year, date_sale__month = date_month).aggregate(Sum('total'))
        return sales_month['total__sum'] if sales_month['total__sum'] != None else 0.0
    
    # método que nos devuelve la cantidad (total comprado) del mes y año actual
    def get_money_related_purchases(self):
        date_month = datetime.now().month
        date_year = datetime.now().year
        purchases_month = Purchase.objects.filter(
            date_purchase__year = date_year, date_purchase__month = date_month).aggregate(Sum('total'))
        return purchases_month['total__sum'] if purchases_month['total__sum'] != None else 0.0


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_sale_month = self.get_money_related_sales()
        total_purchase_month = self.get_money_related_purchases()
        is_bigger_than = True if total_sale_month > total_purchase_month else False
        context['title'] = "Gastos vs Ingresos"
        context['month'] = self.get_name_month()
        context['color'] = self.get_number_color()
        context['sales'] = total_sale_month
        context['purchases'] = total_purchase_month
        context['is_bigger_than'] = is_bigger_than
        return context

core/purchase/views/list_invoices_system/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.purchase.models import Purchase


class ListInvoiceSystemView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, ListView):
    model = Purchase
    paginate_by = 50
    template_name = 'list_invoices_system.html'
    login_url = reverse_lazy('access:Login')
    group_permisson = 'Administrator'

    def __obtain_range_date(self):
        initial_date = self.request.GET['initial_date'] if 'initial_date' in self.request.GET.keys(
        ) else ''
        final_date = self.request.GET['final_date'] if 'final_date' in self.request.GET.keys(
        ) else ''
        return initial_date, final_date

    def get_queryset(self):
        queryset = None
        initial_date, final_date = self.__obtain_range_date()
        if initial_date != '' and final_date != '':
            queryset = Purchase.objects.filter(date_purchase__range=(initial_date, final_date))
        else:
            queryset = Purchase.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Listado de facturas del sistema"
        context["image"] = 'img/list.png'
        context['color'] = self.get_number_color()
        return context

core/purchase/views/options_purchase/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from django.views.generic.base import TemplateView



class OptionsPurchaseView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, TemplateView):
    template_name = 'optionsPurchase.html'
    login_url = reverse_lazy('access:Login')
    group_permisson = 'Administrator'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Opciones de compras"
        context['btn'] = 'Registrar producto'
        context['color'] = self.get_number_color()
        return context

core/purchase/views/upload_invoice/views.py
import json
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from core.app_functions.data_replication import is_actual_state_autoreplication
from core.app_functions.rollback_data import rollback_data
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.product.models import Product, Size
from core.purchase.models import DetailPurchase, Purchase
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.db import transaction


# clase para crear los stock
class UpdloadPurchaseView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, CreateView):
    template_name = 'uploadInvoice.html'
    model = Purchase
    success_url = reverse_lazy('purchae:options')
    login_url = reverse_lazy('access:Login')
    group_permisson = 'Administrator'
    fields = ('iva',)

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    # función que realiza a través de una petición ajax la subida
    # de la factura deseada a nuestro sistema
    def upload_invoice(self, request):
        data = {}
        products = json.loads(request.POST['products'])
        total_invoice = float(request.POST['total'])
        subtotal_purchase = float(request.POST['subtotal'])
        state_replication = is_actual_state_autoreplication()
        try:
            purchase = Purchase()
            purchase.total = total_invoice
            purchase.subtotal = subtotal_purchase
            purchase.save(force_insert=True)
            if state_replication:
                purchase.save(using='mirror_database')
            purchase = Purchase.objects.all().latest('id')
            for product in products:
                detail_invoice = DetailPurchase()
                detail_invoice.purchase = purchase
                product_invoice = Product.objects.get(id = int(product['id']))
                detail_invoice.product = product_invoice
                size_product_invoice = Size.objects.get(id = int(product['size']))
                detail_invoice.size = size_product_invoice
                detail_invoice.ammount = int(product['ammount'])
                detail_invoice.color = product['color']
                detail_invoice.price = float(product['pvp']) / detail_invoice.ammount
                detail_invoice.subtotal = float(product['pvp'])
                detail_invoice.save()
                if state_replication:
                    detail_invoice.save(using='mirror_database')
        except Exception as e:
            data['error'] = str(e)
        return data



    def post(self, request, *args, **kwargs):
        data = {}
        match request.POST['action']:
            # caso de autocomplete para el select2 el el frontend
            case "autocomplete":
                data = []
                product_data = Product.objects.filter(name__icontains = request.POST['term'])
                for product in product_data:
                    item = product.to_json_faster()
                    item['text'] = f'Producto: {product.name}'
                    data.append(item)
            # caso en el que obtenemos un producto que hayamos seleccionado previamente
            case "get_product":
                product_selected = Product.objects.get(id = int(request.POST['id_product']))
                product_selected = product_selected.to_json()
                data['product'] = product_selected
            # caso en el que devolvemos la imagen de un producto y su nombre
            case "image":
                id_prod = int(request.POST['data'])
                product_return = Product.objects.get(id = id_prod)
                data['image'] = product_return.get_image()
                data['name'] = product_return.name
            # caso de hacer efectiva la subida de la factura
            case "upload_invoice":
                with transaction.atomic():
                    data = self.upload_invoice(request)
                    if 'error' in data:
                        rollback_data(3)
            
        return JsonResponse(data, safe=False)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Subir una factura"
        context['list'] = self.success_url
        context['action'] = 'register' 
        context['color'] = self.get_number_color()
        return context

core/purchase/templates/compare_sales_purchases.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static 'img/income.png' %}" class="img-style">
        <h2>Mes {{month}}</h2>
        <div>
            <h4>Ingresos</h4>
            <p>${{sales}}</p>
        </div>
        <div>
            <h4>Gastos</h4>
            <p>${{purchases}}</p>
        </div>
        <div>
            <h4>Comparativa</h4>
            {% if is_bigger_than == True %}
            <div class="alert alert-success" role="alert">
                <strong>Felicitaciones </strong> Las ventas de este mes han superado a los gastos
                aunque eso no quiere decir que haya sido una diferencia abrumadora (en ocasiones)
            </div>
            <a href="#">Resumen de ventas</a>
            {% else %}
            <div class="alert alert-warning" role="alert">
                <strong>Alerta </strong> Las ventas de este mes no han sido lo suficientes para cubrir
                los gatos, realiza promociones, cambia estrategías, para revertir la situación
            </div>
            <a href="#">Resumen de gastos</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

core/purchase/templates/list_invoices_system.html
{% extends 'baseView.html' %} 
{% load static %} 

{% block head %} 
{% endblock %}

{% block content %}
<div class="box-layout">
  <h1>{{title}}</h1>
  <div class="box-content">
    <img src="{% static image %}" alt="" class="img-style" />
    <h4>Filtrar por fecha</h4>
    <form action="{{url}}" method="get">
      <div class="flex-item">
        <div class="cols-3">
          <input type="date" name="initial_date" style="width: 98%;" required>
        </div>
        <div class="cols-3">
          <input type="date" name="final_date" style="width: 98%;" required>
        </div>
        <div class="cols-3">
          <button type="submit" class="btn btn-success">Filtrar</button>
        </div>
      </div>
    </form>
    <table class="table table-responsive table-striped w-auto">
      <thead class="thead-dark" style="width: 100%!important;">
        <tr>
          <th class="w-5">N° Factura</th>
          <th class="w-75">Total</th>
          <th class="w-75">Fecha</th>
          <th class="w-70">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for invoice in page_obj %}
        <tr>
          <td>{{invoice.id}}</td>
          <td>${{invoice.total}}</td>
          <td>{{invoice.date_purchase}}</td>
          <td>
            <a href="#" class="btn btn-danger">Detalles</a>
            <a href="#" class="btn btn-success">PDF</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'pagination_btns.html' %}
  </div>
</div>
{% endblock %}

core/purchase/templates/modal_purchase.html
<div class="modal" tabindex="-1" id="modal"">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Agregar al producto</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <h5>Cantidad </h5>
                    <input type="number" id="amount" class="form-control" min="1"value="1" />
                </div>
                <div class="form-group">
                    <h5>Color</h5>
                    <label>
                        <input type="radio" name="color" value="" id="color1" checked>
                        <span class="swatch"></span>
                    </label>
                    <label>
                        <input type="radio" name="color" value="" id="color2">
                        <span class="swatch"></span>
                    </label>
                    <label>
                        <input type="radio" name="color" value="" id="color3">
                        <span class="swatch"></span>
                    </label>
                </div>
            </div>
            <div class="form-group">
                <h5>Talla</h5>
                <select class="form-control" id="size">
                  
                </select>
            </div>
            <div class="modal-footer">
                <input type="hidden" id="id_product" value="">
                <input type="hidden" id="price" value="">
                <input type="hidden" id="id_local" value="">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success" id="btn-add">Agregar</button>
            </div>
        </div>
    </div>
</div>

core/purchase/templates/optionsPurchase.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/options/styles.css' %}">
{% endblock %}


{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <h3>Panel de administración</h3>
        <div class="flex-item">
            <div class="cols-2">
                <img src="{% static 'img/tools.png' %}" class="image-style">
            </div>
            <div class="cols-2">
                <p><a href="{% url 'purchase:upload' %}" class="btn orange-btn">Agregar facturas</a></p>
                <p><a href="{% url 'purchase:list_invoices' %}" class="btn orange-btn">Listar Facturas</a></p>
                <p><a href="{% url 'purchase:comparation' %}" class="btn orange-btn">Comparacion(Gastos - Ingresos)</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/purchase/templates/uploadInvoice.html
{% extends 'baseView.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/stylesPurchasePage.css' %}">
<link href="{% static 'libs/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
<link href="{% static 'libs/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
<script src="{% static 'libs/select2-4.0.13/js/select2.min.js' %}"></script>
<script src="{% static 'libs/select2-4.0.13/js/i18n/es.js' %}"></script>
<script src="{% static 'js/select2_product_purchase.js' %}"></script>
<script src="{% static 'js/obtain_data_radio_input.js' %}"></script>
<script src="{% static 'js/secondary_function_edit_modal.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/load_data_localstorage.js' %}"></script>
<script src="{% static 'js/make_json_array_product.js' %}"></script>
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static 'img/invoice.png' %}" class="img-style">
        <input type="hidden" name="url" value="#" id="url">
        {% csrf_token %}
        <div class="form-group">
            <label>Nombre del producto</label>
            <select id="product_id" class="select2" style="width: 100%;"></select>
            <button type="button" class="btn btn-primary" id="select-product">Seleccionar</button>
        </div>
        <div id="details-product">
            {% include 'modal_purchase.html' %}
        </div>
        <table class="table table-striped table-responsive" id="table">
            <thead class="thead-dark">
                <tr>
                    <th>Nombre</th>
                    <th class="col-sm-4">Imagen</th>
                    <th class="col-sm-1">Cantidad</th>
                    <th class="col-sm-1">Color</th>
                    <th class="col-sm-2">Precio</th>
                    <th class="col-sm-2">Talla</th>
                    <th class="col-sm-2">Acciones</th>
                </tr>
            </thead>
            <tbody id="t_data">
                
            </tbody>
        </table>
        <h4>Subtotal</h4>
        <p id="subtotal">$0.00</p>
        <h4>Total</h4>
        <p id="total">$0.00</p>
        <button type="submit" class="btn btn-primary" id="btn-purchase">Subir Factura</button>
        <a href="{% url 'purchase:options' %}" class="btn btn-danger">Cancelar</a>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static  'js/upload_invoice.js'%}"></script>
<script src="{% static 'js/add_product_local_storage.js' %}"></script>
<script src="{% static 'js/edit_modal_purchase.js' %}"></script>
<script src="{% static 'js/validate_action.js' %}"></script>
{% endblock %}