config/urls.py
from unittest.mock import patch
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # rutas relacionadas a la página principal tales como dashboard
    path('', include('core.homepage.urls')),
    # rutas relacionadas a los accesos del sistema, tales como ingresar, registrar
    path('access/', include('core.access_system.urls')),
    # rutas relacionadas a los proveedores tales como registrarlos, eliminarlos
    path('supplier/', include('core.supplier.urls')),
    # rutas relacionadas a los productos tales como registrar, eliminar, actualizar
    path('product/', include('core.product.urls')),
    # rutas relacionadas a la tienda tales como visualizar producto, comprar producto
    path('shop/', include('core.store.urls')),
    # rutas relacionadas a el estado actual de envio de los productos
    path('send/', include('core.status_send.urls')),
    # rutas relacionadas a las garantías de los productos e incidentes
    path('warranty/', include('core.warranty.urls')),
    # rutas relacionadas a la cantidad de productos disponibles en el sistema
    path('stock/', include('core.stock.urls')),
    # rutas relacionadas con el usuario
    path('user/', include('core.user.urls')),
    # rutas relacionadas al color de la página
    path('color-page/', include('core.colorpage.urls')),
    # rutas relacionadas con la facturación del usuario
    path('sale/', include('core.sale.urls')),
    # rutas relacionadas con la subida de facturas al sistema
    path('purchase/', include('core.purchase.urls')),
    # rutas relacionadas con la replicación automática de los datos
    path('data-application/', include('core.data.urls')),
    # rutas relacionadas a la administración de los usuarios
    path('user-admin/', include('core.user_admin.urls')),
    # rutas relacionadas con la administración de la aplicacion
    path('admin_site/', include('core.admin_site.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/warranty/urls.py
from django.urls import path
from core.warranty.views.create_warranty.views import CreateWarrantyView
from core.warranty.views.create_warranty_product.views import CreateWarrantyProductView
from core.warranty.views.delete_incidence.views import DeleteIncidenceView
from core.warranty.views.delete_warranty.views import DeleteWarrantyView
from core.warranty.views.edit_incidence.views import EditIncidenceView
from core.warranty.views.edit_warranty.views import EditWarrantyView
from core.warranty.views.edit_warranty_product.views import UpdateWarrantyProductView
from core.warranty.views.list_incidences.views import ListIncidencesView
from core.warranty.views.list_warrantyproduct.views import ListWarrantyProductView
from core.warranty.views.list_warrantys.views import ListWarrantyView
from core.warranty.views.options_warranty.views import OptionsWarrantyView
from core.warranty.views.register_incidence.views import RegisterIncidenceView
from core.warranty.views.view_warranty.views import DetailWarrantyView


app_name = "warranty"
urlpatterns = [
    # ruta para visualizar la garantía del producto
    path('show-warranty/<pk>', DetailWarrantyView.as_view(), name='show-warranty'),
    # ruta para registrar una incidencia 
    path('register-incidence/', RegisterIncidenceView.as_view(), name='register_incidence'),
    # ruta para editar una incidencia 
    path('edit-incidence/<pk>', EditIncidenceView.as_view(), name='edit-incidence'),
    # ruta para eliminar una incidencia
    path('drop-incidence/', DeleteIncidenceView.as_view(), name='delete-incidence'),
    # ruta para listar todas las incidencias del sistema
    path('list-incidence/', ListIncidencesView.as_view(), name='list_incidences'),
    # ruta para crear una nueva garantía
    path('create/', CreateWarrantyView.as_view(), name='create'),
    # ruta para editar una garantía 
    path('edit/<pk>', EditWarrantyView.as_view(), name='edit'),
    # ruta para eliminar una garantía
    path('delete/', DeleteWarrantyView.as_view(), name='delete'),
    # ruta para mostrar las opciones de las garantías
    path('options-warranty/', OptionsWarrantyView.as_view(), name='options_warranty'),
    # ruta para mostrar el listado de garantías 
    path('list/', ListWarrantyView.as_view(), name='list_warranty'),
    # ruta para listar la garantía de los productos
    path('list-warranty-product/', ListWarrantyProductView.as_view(), name='list_warrantyproduct'),
    # ruta para registrar la garantía junto con el producto
    path('create-warranty-product/', CreateWarrantyProductView.as_view(), name='create_warranty_product'),
    # ruta para editar una garantía junto al producto
    path('edit-warranty-product/<pk>', UpdateWarrantyProductView.as_view(), name='edit_warranty_product')
]

core/warranty/views/create_warranty/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from core.app_functions.rollback_data import rollback_data
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.warranty.forms.form_warranty.forms import WarrantyForm
from core.warranty.models import WarrantySale
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction


class CreateWarrantyView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, CreateView):
    template_name = 'createWarranty.html'
    model = WarrantySale
    login_url = reverse_lazy('access:Login')
    success_url = reverse_lazy('warranty:list_warranty')
    group_permisson = 'Administrator'

    # sobrescritura del método post para el guardado de los datos
    def post(self, request, *args, **kwargs):
        data = {}
        with transaction.atomic():
             # obtención de los datos
            form = self.get_form()
            # guardado de los datos
            data = form.save()
            if 'error' in data:
                rollback_data(3)
        # regreso de la respuesta del servidor
        return JsonResponse(data, safe=False)


    def get_form(self):
        return super().get_form(WarrantyForm)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Registrar garantía"
        context['list'] = self.success_url
        context['action'] = 'register' 
        context['btn'] = 'Registrar garantía'
        context['color'] = self.get_number_color()
        return context

core/warranty/views/create_warranty_product/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from core.app_functions.rollback_data import rollback_data
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.warranty.forms.form_warranty_product.forms import WarrantyProductForm
from core.warranty.models import WarrantyProduct
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction


class CreateWarrantyProductView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, CreateView):
    template_name = 'createWarrantyProduct.html'
    model = WarrantyProduct
    login_url = reverse_lazy('access:Login')
    success_url = reverse_lazy('warranty:list_warrantyproduct')
    group_permisson = 'Administrator'

    # sobrescritura del método post para el guardado de los datos
    def post(self, request, *args, **kwargs):
        data = {}
        with transaction.atomic():
             # obtención de los datos
            form = self.get_form()
            # guardado de los datos
            data = form.save()
            if 'error' in data:
                rollback_data(3)
        return JsonResponse(data, safe=False)


    def get_form(self):
        return super().get_form(WarrantyProductForm)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Registrar garantía del producto"
        context['list'] = self.success_url
        context['action'] = 'register' 
        context['btn'] = 'Registrar garantía'
        context['color'] = self.get_number_color()
        return context

core/warranty/views/delete_incidence/views.py
from django.views.generic.base import TemplateView
from core.mixins.emergency_mixin import EmergencyModeMixin


class DeleteIncidenceView(EmergencyModeMixin, TemplateView):
    template_name = 'deleteIncidence.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context["title"] = "Eliminar incidencia"
        context["image"] = "img/trash-incidence.png"
        return context

core/warranty/views/delete_warranty/views.py
from django.views.generic.base import TemplateView
from core.mixins.emergency_mixin import EmergencyModeMixin


class DeleteWarrantyView(EmergencyModeMixin, TemplateView):
    template_name = 'deleteWarranty.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Eliminar garantía'
        context["image"] = 'img/trash-incidence.png'
        return context

core/warranty/views/edit_incidence/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from core.app_functions.rollback_data import rollback_data
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.warranty.forms.form_incidence.form import IncidenceForm
from core.warranty.models import Incidence
from django.db import transaction


class EditIncidenceView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin ,UpdateView):
    template_name = 'editIncidence.html'
    model = Incidence
    login_url = reverse_lazy('access:Login')
    success_url = reverse_lazy('warranty:list_incidences')
    group_permisson = 'Administrator'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    # sobrescritura del método post para el guardado de los datos
    def post(self, request, *args, **kwargs):
        data = {}
        with transaction.atomic():
             # obtención de los datos
            form = self.get_form()
            # guardado de los datos
            data = form.save()
            if 'error' in data:
                rollback_data(3)
        return JsonResponse(data, safe=False)


    def get_form(self):
        return super().get_form(IncidenceForm)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Actualizar incidencia"
        context['list'] = self.success_url
        context['action'] = 'update' 
        context['btn'] = 'Actualizar incidencia'
        context['color'] = self.get_number_color()
        return context

core/warranty/views/edit_warranty/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from core.app_functions.rollback_data import rollback_data
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.warranty.forms.form_warranty.forms import WarrantyForm
from core.warranty.models import WarrantySale
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction


class EditWarrantyView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, UpdateView):
    template_name = 'editWarranty.html'
    model = WarrantySale
    login_url = reverse_lazy('access:Login')
    success_url = reverse_lazy('warranty:list_warranty')
    group_permisson = 'Administrator'
    
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    # sobrescritura del método post para el guardado de los datos
    def post(self, request, *args, **kwargs):
        data = {}
        with transaction.atomic():
             # obtención de los datos
            form = self.get_form()
            # guardado de los datos
            data = form.save()
            if 'error' in data:
                rollback_data(3)
        return JsonResponse(data, safe=False)


    def get_form(self):
        return super().get_form(WarrantyForm)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Actualizar garantía"
        context['list'] = self.success_url
        context['action'] = 'update' 
        context['btn'] = 'Actualizar garantía'
        context['color'] = self.get_number_color()
        return context

core/warranty/views/edit_warranty_product/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from core.app_functions.rollback_data import rollback_data
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.warranty.forms.form_warranty_product.forms import WarrantyProductForm
from core.warranty.models import WarrantyProduct
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction


class UpdateWarrantyProductView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, UpdateView):
    template_name = 'edit_warrantyProduct.html'
    model = WarrantyProduct
    login_url = reverse_lazy('access:Login')
    success_url = reverse_lazy('warranty:list_warrantyproduct')
    group_permisson = 'Administrator'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    # sobrescritura del método post para el guardado de los datos
    def post(self, request, *args, **kwargs):
        data = {}
        with transaction.atomic():
             # obtención de los datos
            form = self.get_form()
            # guardado de los datos
            data = form.save()
            if 'error' in data:
                rollback_data(3)
        return JsonResponse(data, safe=False)


    def get_form(self):
        return super().get_form(WarrantyProductForm)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Actualizar garantía del producto"
        context['list'] = self.success_url
        context['action'] = 'update' 
        context['btn'] = 'Actualizar garantía'
        context['color'] = self.get_number_color()
        return context

core/warranty/views/list_incidences/views.py
from django.urls import reverse_lazy
from core.classes.obtain_color import ObtainColorMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.warranty.models import Incidence



class ListIncidencesView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, ListView):
    model = Incidence
    paginate_by = 10
    template_name = 'listIncidences.html'
    login_url = reverse_lazy('access:Login')
    group_permisson = 'Administrator'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Listado de incidencias"
        context["create"] = reverse_lazy('warranty:register_incidence')
        context["image"] = 'img/list.png'
        context['color'] = self.get_number_color()
        return context

core/warranty/views/list_warrantyproduct/views.py
from django.urls import reverse_lazy
from core.classes.obtain_color import ObtainColorMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.warranty.models import WarrantyProduct



class ListWarrantyProductView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin, ListView):
    model = WarrantyProduct
    paginate_by = 10
    template_name = 'listWarrantyProducts.html'
    login_url = reverse_lazy('access:Login')
    group_permisson = 'Administrator'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Listado de garantías"
        context["create"] = reverse_lazy('warranty:register_incidence')
        context["image"] = 'img/list.png'
        context['color'] = self.get_number_color()
        return context

core/warranty/templates/createWarranty.html
{% extends 'baseView.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
<script src="{% static 'js/functions.js' %}"></script>
{% endblock %}


{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static 'img/warranty.png' %}" class="img-style">
        <input type="hidden" id="value" value="{{list}}">
        <input type="hidden" id="action" value="{{action}}">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label>{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off'}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">{{btn}}</button>
            <a href="{{list}}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'js/validate_action.js' %}"></script>
{% endblock %}

core/warranty/templates/createWarrantyProduct.html
{% extends 'baseView.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
<script src="{% static 'js/functions.js' %}"></script>
{% endblock %}


{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static 'img/warranty.png' %}" class="img-style">
        <input type="hidden" id="value" value="{{list}}">
        <input type="hidden" id="action" value="{{action}}">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label>{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off'}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">{{btn}}</button>
            <a href="{{list}}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'js/validate_action.js' %}"></script>
{% endblock %}

core/warranty/templates/deleteIncidence.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/stylesDeleteIncidence.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static image %}" class="image-style">
        <div class="alert alert-danger" role="alert">
            <strong>Alerta: </strong>Estas a punto de eliminar una incidencia, consulta previamente 
            a un administrador del sistema antes de realizar este movimiento
        </div>
        <form action="">
            <button type="submit" class="btn btn-success">Eliminar incidencia</button>
            <a href="#" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

core/warranty/templates/deleteWarranty.html
{% extends 'baseView.html' %}
{% load static %}


{% block head %}
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static image %}" id="image-class">
        <div class="alert alert-danger" role="alert">
            <strong>Precaución: </strong>Estas a punto de eliminar una garantía, el no hacerlo
            de manera consciente, puede ocasionar pérdida de datos, ¿Estás seguro de continuar?
        </div>
        <form>
            <button type="button" class="btn btn-success">Eliminar</button>
            <a href="#" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

core/warranty/templates/detailWarranty.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <div class="flex-item">
            <div class="cols-2">
                <img src="{% static 'img/warranty.png' %}">
            </div>
            <div class="cols-2">
                <h4>Descripción</h4>
                <p>{{object.description}}</p>
                <h4>Meses cubiertos</h4>
                <p>{{object.months_coverred}}</p>
                <h4>Incidencias cubiertas</h4>
                <ul>
                    {% for incidence in object.incidence.all %}
                    <li>{{incidence}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}


core/warranty/templates/editIncidence.html
{% extends 'registerIncidence.html' %}

core/warranty/templates/editWarranty.html
{% extends 'createWarranty.html' %}

core/warranty/templates/edit_warrantyProduct.html
{% extends 'createWarrantyProduct.html' %}

core/warranty/templates/listIncidences.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/list_categories/styles.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static image %}" alt="" class="img-style">
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th class="w-5">ID</th>
                    <th class="w-25">Nombre inciencia</th>
                    <th class="w-25">Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for incidence in page_obj %}
                <tr>
                    <td scope="row">{{incidence.id}}</td>
                    <td>{{incidence.name}}</td>
                    {% if incidence.is_active == True %}
                    <td><strong>Activo</strong></td>
                    {% endif %}
                    {% if incidence.is_active == False %}
                    <td><strong>Baja</strong></td>
                    {% endif %}
                    <td><a class="btn btn-warning" href="../edit-incidence/{{incidence.id}}">Editar</a>
                    <a class="btn btn-success" href="#">Detalles</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'warranty:register_incidence' %}" class="btn btn-primary">Agregar nueva incidencia</a>
        {% include 'pagination_btns.html' %}
    </div>
</div>
{% endblock %}

core/warranty/templates/listWarrantyProducts.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/list_categories/styles.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static image %}" alt="" class="img-style">
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th class="w-5">ID</th>
                    <th class="w-25">Nombre garantia</th>
                    <th class="w-25">Nombre producto</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for warranty_product in page_obj %}
                <tr>
                    <td scope="row">{{warranty_product.id}}</td>
                    <td>{{warranty_product.warranty.name}}</td>
                    <td>{{warranty_product.product.name}}</td>
                    <td><a class="btn btn-warning" href="../edit-warranty-product/{{warranty_product.id}}">Editar</a>
                    <a class="btn btn-success" href="">Detalles</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'warranty:create_warranty_product' %}" class="btn btn-primary">Agregar nueva garantia</a>
        {% include 'pagination_btns.html' %}
    </div>
</div>
{% endblock %}

core/warranty/templates/listWarrantys.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/list_categories/styles.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static image %}" alt="" class="img-style">
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th class="w-5">ID</th>
                    <th class="w-25">Nombre garantia</th>
                    <th class="w-25">Meses cubiertos</th>
                    <th class="w-25">Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for warranty in page_obj %}
                <tr>
                    <td scope="row">{{warranty.id}}</td>
                    <td>{{warranty.name}}</td>
                    <td>{{warranty.months_coverred}}</td>
                    {% if warranty.is_active == True %}
                    <td><strong>Activo</strong></td>
                    {% endif %}
                    {% if warranty.is_active == False %}
                    <td><strong>Baja</strong></td>
                    {% endif %}
                    <td><a class="btn btn-warning" href="../edit/{{warranty.id}}">Editar</a>
                    <a class="btn btn-success" href="../show-warranty/{{warranty.id}}">Detalles</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'warranty:create' %}" class="btn btn-primary">Agregar nueva garantia</a>
        {% include 'pagination_btns.html' %}
    </div>
</div>
{% endblock %}

core/warranty/templates/options_warranty.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/options/styles.css' %}">
{% endblock %}


{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <h3>Panel de administración</h3>
        <div class="flex-item">
            <div class="cols-2">
                <img src="{% static 'img/tools.png' %}" class="image-style">
            </div>
            <div class="cols-2">
                <p><a href="{% url 'warranty:list_incidences' %}" class="btn orange-btn">Incidencias</a></p>
                <p><a href="{% url 'warranty:list_warranty' %}" class="btn orange-btn">Garantías(Usuarios)</a></p>
                <p><a href="{% url 'warranty:list_warrantyproduct' %}" class="btn orange-btn">Garantías(Productos)</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/warranty/templates/registerIncidence.html
{% extends 'baseView.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
<script src="{% static 'js/functions.js' %}"></script>
{% endblock %}


{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <img src="{% static 'img/incidence.png' %}" class="img-style">
        <input type="hidden" id="value" value="{{list}}">
        <input type="hidden" id="action" value="{{action}}">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label>{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off'}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">{{btn}}</button>
            <a href="{{list}}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'js/validate_action.js' %}"></script>
{% endblock %}

core/warranty/templates/warrantyProduct.html
|{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/stylesWarrantyProduct.css' %}">
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <div class="row">
            <div class="col-middle">
                <img src="{% static image %}" class="image-style">
            </div>
            <div class="col-middle">
                <h3>Producto: Vestido primaveral</h3>
                <p>
                    Phasellus ac sem eget quam pharetra suscipit. Aenean arcu augue, tincidunt eu iaculis a, sollicitudin id lacus. 
                    Cras a accumsan leo. Sed pretium vehicula nisi, a ultrices metus rutrum ut. Maecenas ut pellentesque massa. 
                    Fusce gravida elementum feugiat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
                </p>
                <strong>Número de la factura: </strong> 12345678
            </div>
            <div>
                <p><strong>Precio de compra: </strong> $130.51</p>
                <p><strong>Fecha inicio garantía: </strong> 11/02/21</p>
                <p><strong>Fecha fin garanía: </strong> 11/05/21</p>
                <p><strong>Status: </strong> Active</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}