config/urls.py
from unittest.mock import patch
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # rutas relacionadas a la página principal tales como dashboard
    path('', include('core.homepage.urls')),
    # rutas relacionadas a los accesos del sistema, tales como ingresar, registrar
    path('access/', include('core.access_system.urls')),
    # rutas relacionadas a los proveedores tales como registrarlos, eliminarlos
    path('supplier/', include('core.supplier.urls')),
    # rutas relacionadas a los productos tales como registrar, eliminar, actualizar
    path('product/', include('core.product.urls')),
    # rutas relacionadas a la tienda tales como visualizar producto, comprar producto
    path('shop/', include('core.store.urls')),
    # rutas relacionadas a el estado actual de envio de los productos
    path('send/', include('core.status_send.urls')),
    # rutas relacionadas a las garantías de los productos e incidentes
    path('warranty/', include('core.warranty.urls')),
    # rutas relacionadas a la cantidad de productos disponibles en el sistema
    path('stock/', include('core.stock.urls')),
    # rutas relacionadas con el usuario
    path('user/', include('core.user.urls')),
    # rutas relacionadas al color de la página
    path('color-page/', include('core.colorpage.urls')),
    # rutas relacionadas con la facturación del usuario
    path('sale/', include('core.sale.urls')),
    # rutas relacionadas con la subida de facturas al sistema
    path('purchase/', include('core.purchase.urls')),
    # rutas relacionadas con la replicación automática de los datos
    path('data-application/', include('core.data.urls')),
    # rutas relacionadas a la administración de los usuarios
    path('user-admin/', include('core.user_admin.urls')),
    # rutas relacionadas con la administración de la aplicacion
    path('admin_site/', include('core.admin_site.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/data/urls.py
from django.urls import path

from core.data.views.update_datarepplication.views import UpdateDataRepplicationView


app_name = 'data'
urlpatterns = [
    # ruta para actualizar la autoreplicación de los datos
    path('update/', UpdateDataRepplicationView.as_view(), name='update_rep')
]

core/homepage/urls.py
from django.urls import path
from core.homepage.views.about.views import AboutPageView
from core.homepage.views.dashboard_admin.views import DashboardAdminView
from core.homepage.views.dashboard_user.views import DashboardUserView
from core.homepage.views.error_page.views import ErrorPageView

from core.homepage.views.home.views import HomepageView
from core.homepage.views.not_found_404.views import Template404View
from core.homepage.views.our_mission.views import OurMissionPageView
from core.homepage.views.state_page.views import StatePageView
from core.homepage.views.support_email.views import SupportEmailView
from core.homepage.views.test_databases.views import StateDatabasesView
from core.homepage.views.user_flow.views import UserPageFlowView
app_name = 'app_views'

urlpatterns = [
    # paths for the mainpage
    path('', HomepageView.as_view(), name='homepage'),
    # ruta para el dashboard del usuario
    path('dashboard-user/', DashboardUserView.as_view(), name='dashboard_user'),
    # ruta para el dashboard del administrador
    path('dashboard-admin/', DashboardAdminView.as_view(), name='dashboard_admin'),
    # ruta para la página de error 404
    path('404/', Template404View.as_view(), name='404_page'),
    # ruta para la pagina de flujo de usuarios
    path('flow-users/', UserPageFlowView.as_view(), name='flow_users'),
    # ruta para obtener el estado de la página
    path('state-page/', StatePageView.as_view(), name='state_page'),
    # ruta para obtener el estado actual de las bases de datos
    path('state-databases/', StateDatabasesView.as_view(), name='state_databases'),
    # ruta para manejar el estado de protección de la página
    path('error/', ErrorPageView.as_view(), name='error_page'),
    # ruta para ver un about del sitio
    path('about', AboutPageView.as_view(), name='about'),
    # ruta para ver las misiones de la compañia
    path('our-mission/', OurMissionPageView.as_view(), name='our_mission'),
    # ruta para mostrar el correo de soporte del sitio
    path('support-team/', SupportEmailView.as_view(), name='support_team')
]

core/sale/urls.py
from django.urls import path
from core.sale.views.detail_invoice.views import DetailInvoiceView

from core.sale.views.list_invoice.views import ListInvoiceView
from core.sale.views.render_pdf_invoice.views import RenderDetailInvoiceView


app_name = 'sale'
urlpatterns = [
    # ruta para listar las facturas del usuario actual
    path('list-invoices/', ListInvoiceView.as_view(), name='list_invoices'),
    # ruta para obtener los detalles de la factura actual
    path('detail-invoice/<pk>', DetailInvoiceView.as_view(), name='detail_invoice'),
    # ruta para generar el pdf de la factura
    path('render-pdf-invoice/<pk>', RenderDetailInvoiceView.as_view(), name='render_pdf')
]

core/store/urls.py
from django.urls import path
from core.store.views.add_comment.views import AddComentProduct
from core.store.views.cancel.views import CancelPaymentView
from core.store.views.list_all_comments_products.views import ListAllCommentsProduct
from core.store.views.list_all_products.views import ListAllProductsView
from core.store.views.list_best_ranking_prod.views import ListBestProductsView
from core.store.views.list_categories.views import ListCategoryShopView
from core.store.views.list_discount_prod.views import ListDiscountProductView
from core.store.views.list_products.views import ListProductsShopView
from core.store.views.list_search_prod.views import ListSearchProductView
from core.store.views.shopCart.views import ShopCartView

from core.store.views.showProduct.views import DetailProductView
from core.store.views.shop.views import MainShopView
from core.store.views.success.views import SuccessPaymentView


app_name = "shop"
urlpatterns = [
    # vista acerca de la vista a detalle del producto para su compra
    path('detail-product/<int:pk>', DetailProductView.as_view(), name='detail_product'),
    # vista relacionada al carrito de compra 
    path('shop-cart/', ShopCartView.as_view(), name='shop_cart'),
    # vista relacionada a la página principal de la tienda
    path('', MainShopView.as_view(), name='main_shop'),
    # vista relacionada a mostrar en lista los productos de la tienda
    path('list/<int:id_category>', ListProductsShopView.as_view(), name='list_products'),
    # vista relacionada a mostrar todas las categorías de la tienda (cliente),
    path('list-categories/', ListCategoryShopView.as_view(), name='list_category_shop'),
    # vista para mostrar los productos con descuento
    path('list-discount/', ListDiscountProductView.as_view(), name='list_discount'),
    # vista relacionada a mostrar los productos con mejor valoración
    path('list-bests/', ListBestProductsView.as_view(), name='list_best_products'),
    # vista relacionada a ver todos los productos
    path('list-all/', ListAllProductsView.as_view(), name='list_all'),
    # vista relacionada a desplegar los productos relacionados a la búsqueda
    path('list-search/', ListSearchProductView.as_view(), name='list_search'),
    path('list-search/<str:name>', ListSearchProductView.as_view(), name='list_search_s'),
    # vista relacionada a agregar los comentarios de un producto
    path('add-comment-product/<int:id_product>', AddComentProduct.as_view(), name='add_comment'),
    # vista relacionada a mostrar los comentarios de un producto
    path('view-comments-product/<int:id_product>', ListAllCommentsProduct.as_view(), name='list_comments'),
    # ruta de la vista de cancelación de la compra
    path('cancel/', CancelPaymentView.as_view(), name='cancel'),
    # ruta de pago exitoso
    path('success/', SuccessPaymentView.as_view(), name='success')
]

core/user/urls.py
from django.urls import path
from core.user.views.edit_direction.views import UpdateUserDirectionView
from core.user.views.edit_password_login.views import EditPasswordLoginView
from core.user.views.list_directions.views import ListDirectionUserView
from core.user.views.make_unactive_user.views import EditStatusActualUser
from core.user.views.register_direction.views import RegisterDirectionUser

from core.user.views.user_edit.views import UpdateUserView
from core.user.views.user_view.views import ProfileUserView

app_name = 'user'
urlpatterns = [
    # ruta para poder editar el perfil del usuario
    path('edit-profile/', UpdateUserView.as_view(), name='profile_edit'),
    # ruta para visualizar el perfil del usuario
    path('view-profile/', ProfileUserView.as_view(), name='view_profile'),
    # ruta para listar las direcciones registradas del usuario
    path('directions/', ListDirectionUserView.as_view(), name='list_directions'),
    # ruta para registrar las direcciones del usuario
    path('register-direction/', RegisterDirectionUser.as_view(), name='register_direction'),
    # ruta para editar una dirección del usuario
    path('edit-direction/<int:pk>', UpdateUserDirectionView.as_view(), name='edit_direction'),
    # ruta para actualizar la contraseña del usuario
    path('edit-password/', EditPasswordLoginView.as_view(), name='edit_password'),
    # ruta para dar de baja la cuenta
    path('make-inactive/', EditStatusActualUser.as_view(), name='make_inactive')
]

core/homepage/models.py
from django.db import models

# Create your models here.

core/homepage/views/about/views.py
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin

# template view for the main page
class AboutPageView(EmergencyModeMixin, TemplateView, ObtainColorMixin):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Acerca de nosotros"
        context['color'] = self.get_number_color()
        return context

core/homepage/views/dashboard_admin/views.py
from datetime import datetime, timedelta
import json
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.mixins import ValidateSessionGroupMixin
from core.product.models import Category
from core.sale.models import DetailSale, Sale
from django.http import HttpResponse, JsonResponse
from core.mixins.emergency_mixin import EmergencyModeMixin
from django.db.models import Sum
import requests


class DashboardAdminView(EmergencyModeMixin, LoginRequiredMixin, ValidateSessionGroupMixin, ObtainColorMixin,TemplateView):
    template_name = 'dashboardAdmin.html'
    login_url = reverse_lazy('access:Login')
    group_permisson = 'Administrator'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_number_sale_per_category(self):
        categories = Category.objects.all()
        list_number_sale_per_category = []
        for category in categories:
            sale_number = DetailSale.objects.filter(product__category = category).count()
            list_number_sale_per_category.append(sale_number)
        return list_number_sale_per_category
    
    def get_names_categories(self):
        list_names_categories = []
        categories = Category.objects.all()
        for category in categories:
            list_names_categories.append(category.name)
        return list_names_categories
    
    def get_sales_by_month(self):
        date_time_month = datetime.now().month
        date_time_year = datetime.now().year
        sale_num = Sale.objects.filter(
            date_sale__month = date_time_month, date_sale__year = date_time_year).aggregate(Sum('total'))
        return sale_num.get('total__sum') if sale_num.get('total__sum') != None else 0.0
    
    def get_sales_by_month_for_ia(self):
        max_month = datetime.now().month - 1
        current_month = 1
        current_year = datetime.now().year
        list_sales_per_month = []
        list_of_month = []
        while current_month <= max_month:
            sale_of_month = Sale.objects.filter(
                date_sale__month = current_month, date_sale__year = current_year).aggregate(Sum('total'))
            value_sale_month = float(sale_of_month.get('total__sum')) if sale_of_month.get('total__sum') != None else 0.0
            list_sales_per_month.append(value_sale_month)
            list_of_month.append(current_month)
            current_month += 1
        return list_sales_per_month, list_of_month
    
    def get_sales_by_week(self):
        list_sale_days = []
        counter = 6
        while counter >= 0:
            date = (datetime.now() - timedelta(counter)) 
            sales_per_day =  Sale.objects.filter(date_sale = date).aggregate(Sum('total'))
            sale = sales_per_day['total__sum']
            if sale is not None:
                sale = str(sale)
                sale = float(sale)
                list_sale_days.append(sale)
            else:
                list_sale_days.append(0.0)
            counter -= 1
        print(list_sale_days)
        return list_sale_days
    
    # function allows to send to api_ia data for prediction of sale of week
    def __request_prediction_week_from_api(self):
        uri = "http://localhost:8080/sale/prediction/"
        body = {
            "data_x" : [1, 2 ,3 ,4 ,5 , 6, 7],
            "data_y" : self.get_sales_by_week(),
            "data_predict" : 8
        }
        response = requests.get(uri, json = body)
        return response.json()
    
    # function allows to send to api_ia data for prediction of sale of month
    def __request_prediction_month_from_api(self):
        sales_per_month, list_months = self.get_sales_by_month_for_ia()
        uri = "http://localhost:8080/sale/prediction/"
        body = {
            "data_x" : list_months,
            "data_y" : sales_per_month,
            "data_predict" : datetime.now().month
        }
        response = requests.get(uri, json = body)
        return response.json()
    

    
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            match request.POST['action']:
                case 'pie_g':
                    data['number_sale'] = self.get_number_sale_per_category()
                    data['labels'] = self.get_names_categories() 
                case 'bar_month':
                    data['sale_month'] = self.get_sales_by_month() 
                case 'bar_week':
                    data['sale_week'] = self.get_sales_by_week()
                case 'prediction_sale_week':
                    data = self.__request_prediction_week_from_api()
                case 'prediction_sale_month':
                    data = self.__request_prediction_month_from_api()   
        except Exception as e:
            data['error'] = str(e)
            print(data)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Dashboard'
        context['status'] = reverse_lazy('status_send:list')
        context['supplier'] = reverse_lazy('supplier_app:list_supplier')
        context['products'] = reverse_lazy('product:list_product')
        context['stock'] = reverse_lazy('stock:list_stock')
        context['store'] = reverse_lazy('shop:main-shop')
        context['color'] = self.get_number_color()
        return context

core/homepage/views/error_page/views.py
from django.views.generic.base import TemplateView


class ErrorPageView(TemplateView):
    template_name = 'warning_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Error del sistema'
        return context

core/homepage/views/home/views.py
from itertools import product
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from core.classes.obtain_color import ObtainColorMixin
from core.mixins.emergency_mixin import EmergencyModeMixin
from core.product.models import Product

# template view for the main page
class HomepageView(EmergencyModeMixin, TemplateView, ObtainColorMixin):
    template_name = 'index.html'

    # method that return best products for the shop
    def best_ranking_products(self):
        best_ranking = Product.objects.filter(product_rating__gt = 3.0).order_by('-product_rating')
        return best_ranking

    def get_context_data(self, **kwargs):
        products = self.best_ranking_products()
        context = super().get_context_data(**kwargs)
        context["title"] = "Shop IA online"
        context['signin'] = reverse_lazy('access:signin')
        context['best_products'] = products[1:]
        context['best_product'] = products[0]
        context['color'] = self.get_number_color()
        return context

core/homepage/views/not_found_404/views.py
from django.views.generic.base import TemplateView


class Template404View(TemplateView):
    template_name = '404.html'

core/homepage/templates/dashboardAdmin.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/dashboard_admin/styles.css' %}">
<script src="{% static 'js/array_color.js' %}"></script>
<script src="{% static 'js/dashboard_admin/chart.js' %}"></script>
<script src="{% static 'js/dashboard_admin/bar_chart.js' %}"></script>
<script src="{% static 'js/dashboard_admin/filled_line_chart.js' %}"></script>
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-dashboard">
        {% csrf_token %}
        {% include 'modal_predictions.html' %}
        {% include 'modal_predictions_month.html' %}
        <h2>Opciones administrador</h2>
        <div class="flex-item">
            <div class="cols-4 box-shadowed">
                <h3>Administración</h3>
                <p><a href="{% url 'color:update_page' %}" class="btn orange-btn btn-style">Color página</a></p>
                <p> <a href="{% url 'purchase:options' %}" class="btn orange-btn btn-style">Compras</a></p>
                <p><a href="{{stock}}" class="btn orange-btn btn-style">Stock</a></p>
                <p><a href="{% url 'admin_site:update_emergency_app' %}" class="btn orange-btn btn-style">Modo de emergencia</a></p>
            </div>
            <div class="cols-4 box-shadowed">
                <h3>Usuarios</h3>
                <p><a href="{% url 'user_admin:list_super_user' %}" class="btn orange-btn btn-style">Super Usuarios</a></p>
                <p><a href="{% url 'user_admin:list_admin_user' %}" class="btn orange-btn btn-style">Usuarios administradores</a></p>
                <p><a href="{% url 'user_admin:list_block_user' %}" class="btn orange-btn btn-style">Eliminar usuarios</a></p>
                <p><a href="{% url 'user_admin:massive_email' %}" class="btn orange-btn btn-style">Correos masivos</a></p>
            </div>
            <div class="cols-4 box-shadowed">
                <h3>Tienda</h3>
                <p><a href="{{supplier}}" class="btn orange-btn btn-style">Proveedores</a></p>
                <p><a href="{% url 'warranty:options_warranty' %}" class="btn orange-btn btn-style">Garantías</a></p>
                <p><a href="{% url 'product:options' %}" class="btn orange-btn btn-style">Productos</a></p>
                <p><a href="{% url 'status_send:options' %}" class="btn orange-btn btn-style">Estados de envio</a></p>
            </div>
            <div class="cols-4 box-shadowed">
                <h3>Opciones</h3>
                <p><a href="{% url 'data:update_rep' %}" class="btn orange-btn btn-style">Respaldos automáticos</a></p>
                <p><a href="{% url 'app_views:flow_users' %}" class="btn orange-btn btn-style">Flujo de usuarios</a></p>
                <p><a href="{% url 'app_views:state_page' %}" class="btn orange-btn btn-style">Estado página</a></p>
                <p><a href="{% url 'app_views:state_databases' %}" class="btn orange-btn btn-style">Estado bases de datos</a></p>
            </div>
        </div>
        <h2>Estádisticas</h2>
        <div class="chart-style">
            <h3>Ventas de la semana</h3>
            <canvas id="myChart"></canvas>
            <button class="btn btn-primary" id="predict_sales_week">Predicción de ventas</button>
            <hr>
        </div>
        <div class="chart-style">
            <h3>Ventas del mes</h3>
            <canvas id="line-chart"></canvas>
            <button class="btn btn-primary" id="predict_sales_month">Predicción de ventas</button>
            <hr>
        </div>
        <div class="chart-style">
            <h3>Categorias más vendidas</h3>
            <canvas id="graphic"></canvas>
            <a class="btn btn-primary" href="#">Más detalles</a>
            <a class="btn btn-warning" href="#">Administración</a>
            <button class="btn btn-outline-dark" id="categories">Obtener categorias</button>
            <hr>
        </div>
        <input type="hidden" id="url" value="{% url 'app_views:dashboard_admin' %}">
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/dashboard_admin/requestIA.js' %}"></script>
{% endblock %}

core/homepage/templates/dashboardUser.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/dashboard_user/styles.css' %}">
<script src="{% static 'js/array_color.js' %}"></script>
<script src="{% static 'js/dashboard_user/chart.js' %}"></script>
{% endblock %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="main-box">
        <h2>Opciones usuario</h2>
        {% csrf_token %}
        <div class="flex-item">
            <div class="cols-3 box-shadowed">
                <h3>Perfil</h3>
                <p><a href="{% url 'user:view_profile' %}" class="btn orange-btn btn-style">Ver perfil</a></p>
                <p> <a href="{% url 'user:profile_edit' %}" class="btn orange-btn btn-style">Editar perfil</a></p>
                <p><a href="{% url 'user:edit_password' %}" class="btn orange-btn btn-style">Cambiar contraseña</a></p>
                <p><a href="{% url 'user:list_directions' %}" class="btn orange-btn btn-style">Agenda de direcciones</a></p>
            </div>
            <div class="cols-3 box-shadowed">
                <h3>Compras</h3>
                <p><a href="{% url 'sale:list_invoices' %}" class="btn orange-btn btn-style">Facturas</a></p>
                <p> <a href="{% url 'status_send:list_status_send_user' %}" class="btn orange-btn btn-style">Estado envio productos</a></p>
                <p><a href="{% url 'shop:list_discount' %}" class="btn orange-btn btn-style">Mejores ofertas</a></p>
                <p><a href="{% url 'shop:list_best_products' %}" class="btn orange-btn btn-style">Mejores productos</a></p>
            </div>
            <div class="cols-3 box-shadowed">
                <h3>En desarrollo...</h3>
                <p><a href="{% url 'user:make_inactive' %}" class="btn orange-btn btn-style">Dar de baja la cuenta</a></p>
                <p> <a href="{% url 'app_views:support_team' %}" class="btn orange-btn btn-style">Contacto con el equipo administrador</a></p>
                <p><a href="{% url 'access:logout_all' %}" class="btn orange-btn btn-style">Cerrar todas las sesiones: {{number_sessions}}</a></p>
                <p><a href="" class="btn orange-btn btn-style">Más...</a></p>
            </div>
        </div>
        <h3>Ultimos productos comprados</h3>
        <div class="flex-item">
            {% for product in last_products %}
            <div class="cols-{{class_css}} card-product">
                <h5>{{product.name}}</h5>
                <img src="{{product.get_image}}" alt="" class="image-card">
                <a class="btn btn-primary" href="../shop/detail-product/{{product.id}}">Ver más</a>
            </div>
            {% endfor %}
        </div>
        <a href="{% url 'sale:list_invoices' %}" class="btn btn-success">Ver todas las compras</a>
        <h3>Perfil de usuario</h3>
        <div class="flex-item information-user">
            <div class="cols-2">
                <img src="{{ request.user.get_image }}" class="image-profile">
            </div>
            <div class="cols-2">
                <p><strong>Fecha de último inicio de sesión: </strong>{{last_login_date}}</p>
                <p><strong>Fecha ultíma compra: </strong>{{date_last_bought}}</p>
                <p><strong>Nombre: </strong>{{request.user.first_name}}</p>
                <p><strong>Apellidos: </strong>{{request.user.last_name}}</p>
                <a href="{% url 'user:view_profile' %}" class="btn btn-warning">Más información</a>
                <a href="{% url 'user:list_directions' %}" class="btn btn-primary">Agenda direcciones</a>
                <a href="{% url 'user:edit_password' %}" class="btn btn-danger">Cambiar contraseña</a>
            </div>
        </div>
        <h3>Estadisticas de compras por categoría</h3>
        <canvas id="graphic"></canvas>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

core/homepage/templates/emailSupport.html
{% extends 'baseView.html' %}
{% load static %}

{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <div class="box-content">
        <div class="card text-left">
            <div class="card-body">
              <h4 class="card-title"><strong>Ayuda</strong></h4>
              <p class="card-text">
                <strong>Correo electrónico: </strong> support@shopia@gmail.com<br/>
                El correo mostrado en el parrafo anterior es únicamente para soporte relacionado a 
                problemas con el acceso a tu cuenta, pagos realizados pero con estado de pago pendiente, etc. 
                
              </p>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

core/homepage/templates/index.html
{% extends 'baseView.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/stylesHome.css' %}">
{% endblock head %}


{% block content %}
<div class="box-layout">
    <h1>{{title}}</h1>
    <h3>¿Que es Shop IA online?</h3>
    <div class="main-text flex-item">
        <div class="cols-2">
            <p>
                Suspendisse potenti. Vestibulum ut porttitor massa, sed lobortis nisl. Sed cursus quam ac tellus faucibus
                mattis. Fusce sit amet lectus diam.
                Donec blandit turpis vel massa dictum, id consequat sem hendrerit. Nullam ac purus et ligula lobortis
                viverra euismod eget lorem.
                Fusce vestibulum sapien neque, quis luctus dui maximus vel. Ut laoreet augue non metus pretium gravida.
                Etiam non fermentum purus, eget lacinia ligula.
                Integer pretium magna id ex aliquet, vel tempor neque fringilla. Nullam nibh ligula, congue ac maximus a,
                accumsan elementum massa.
                Mauris viverra elit neque, in hendrerit mi tempor ac. Sed mollis iaculis sodales. Maecenas vestibulum sit
                amet ante at molestie.
            </p>
            <a href="{{signin}}" class="btn btn-success">Crear cuenta</a>
        </div>
        <div class="cols-2">
            <img src="{% static 'img/paisaje.jpg' %}" class="main-image">
        </div>
    </div>
    <div class="main-image">
        <h3>Selección de nuestros mejores productos</h3>
        {% include 'carrousel.html' %}
    </div>
    <div class="flex-item">
        <div class="cols-2">
            <h3>Acerca de nosotros</h3>
            <p>
                Suspendisse potenti. Vestibulum ut porttitor massa, sed lobortis nisl. Sed cursus quam ac tellus
                faucibus mattis. Fusce sit amet lectus diam.
                Donec blandit turpis vel massa dictum, id consequat sem hendrerit. Nullam ac purus et ligula lobortis
                viverra euismod eget lorem.
                Fusce vestibulum sapien neque, quis luctus dui maximus vel. Ut laoreet augue non metus pretium gravida.
                Etiam non fermentum purus, eget lacinia ligula.
                Integer pretium magna id ex aliquet, vel tempor neque fringilla. Nullam nibh ligula, congue ac maximus
                a, accumsan elementum massa.
                Mauris viverra elit neque, in hendrerit mi tempor ac. Sed mollis iaculis sodales. Maecenas vestibulum
                sit amet ante at molestie.
            </p>
            <a class="btn btn-primary" href="{% url 'app_views:about' %}">Más información</a>
        </div>
        <div class="cols-2">
            <h3>Mision</h3>
            <p>
                Suspendisse potenti. Vestibulum ut porttitor massa, sed lobortis nisl. Sed cursus quam ac tellus
                faucibus mattis. Fusce sit amet lectus diam.
                Donec blandit turpis vel massa dictum, id consequat sem hendrerit. Nullam ac purus et ligula lobortis
                viverra euismod eget lorem.
                Fusce vestibulum sapien neque, quis luctus dui maximus vel. Ut laoreet augue non metus pretium gravida.
                Etiam non fermentum purus, eget lacinia ligula.
                Integer pretium magna id ex aliquet, vel tempor neque fringilla. Nullam nibh ligula, congue ac maximus
                a, accumsan elementum massa.
                Mauris viverra elit neque, in hendrerit mi tempor ac. Sed mollis iaculis sodales. Maecenas vestibulum
                sit amet ante at molestie.
            </p>
            <a class="btn btn-primary" href="{% url 'app_views:our_mission' %}">Más información</a>
        </div>
    </div>
    <div>
        <h3>Información de contacto</h3>
    </div>
</div>

{% endblock %}